### PR TITLE
Update sphinx to 1.5.1 

### PR DESCRIPTION
**Pull request by martianyi**
According to this issue https://github.com/sphinx-doc/sphinx/issues/3212, docutils 0.13.1 has caused our docs generation to fail. This updates the sphinx requirement to 1.5.1 and fix the issue.

### CODE REVIEW

**Comment by ericholscher** [comment]
I believe 1.5 has issues with our theme which we need to release to fix. You can set the Sphinx version on your project in your requirements.txt, and we'll respect it.

**Comment by martianyi** [comment]
I don't know if I were wrong, but according to my test, this tool installed sphinx 1.3.1 despite what I set in my requirements.txt. Anyway, last test on my computer sphinx 1.3.1 and docutils 0.13.1 works fine together.

**Comment by agjohnson** [comment]
I'll set this as blocked then, until we address theme issues.

**Comment by ericholscher** [comment]
We can now properly depend on 1.5, as it's the default on the builders in prod. Merging.

**Pull request merged**
